
services:
  # PHP App
  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: doanbe2-php
    container_name: doanbe2-app
    restart: unless-stopped
    working_dir: /var/www
    volumes:
      - ./:/var/www
      - ./uploads.ini:/usr/local/etc/php/conf.d/uploads.ini
    networks:
      - doanbe2-network

  # Nginx Web Server
  webserver:
    image: nginx:stable-alpine
    container_name: doanbe2-webserver
    restart: unless-stopped
    ports:
      - "8000:80"
    volumes:
      - ./:/var/www
      - ./docker_config/nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - app
    networks:
      - doanbe2-network

  # MySQL Database
  db:
    image: mysql:8.0
    container_name: doanbe2-db
    restart: unless-stopped
    ports:
      - "3306:3306"
    environment:
      MYSQL_DATABASE: doanbe2_db
      MYSQL_ROOT_PASSWORD: root
      MYSQL_PASSWORD: root
      MYSQL_USER: user
    volumes:
      - dbdata:/var/lib/mysql
    networks:
      - doanbe2-network

  # phpMyAdmin
  phpmyadmin:
    image: phpmyadmin
    container_name: doanbe2-pma
    restart: unless-stopped
    ports:
      - "8080:80"
    environment:
      PMA_HOST: db
    depends_on:
      - db
    networks:
      - doanbe2-network

  # Node + Vite
  node:
    image: node:20
    container_name: doanbe2-node
    working_dir: /var/www
    tty: true
    volumes:
      - ./:/var/www
      - node_modules:/var/www/node_modules
    ports:
      - "5173:5173"
    command: sh -c "npm install && npm run dev -- --host 0.0.0.0"
    networks:
      - doanbe2-network

  # Laravel Reverb
  reverb:
    build:
      context: .
      dockerfile: Dockerfile
    image: doanbe2-php
    container_name: doanbe2-reverb
    restart: unless-stopped
    working_dir: /var/www
    volumes:
      - ./:/var/www
    command: >
      sh -c "
        sleep 15 &&
        php artisan optimize:clear &&
        php artisan reverb:start --host=0.0.0.0 --port=8080
      "
    ports:
      - "8081:8080"
    depends_on:
      - app
      - db
    networks:
      - doanbe2-network


networks:
  doanbe2-network:
    driver: bridge

volumes:
  dbdata:
    driver: local

  node_modules:

